meta_product_name: "Bloom"
meta_title: "Bloom - Your Ingredient Safety Companion"
meta_description: "A comprehensive product ingredient support service. We help regular you make informed, scientifically based decisions about your product choices"
meta_image: "cover_image.png" # should exist in `app/assets/images/`
