meta_product_name: "Bloom"
meta_title: "Bloom - Your Ingredient Safety Companion"
meta_description:  “Buy cosmetics with complete trust and serenity. Take the research and guessing out of buying new products with our comprehensive and science-based guide. Bloom helps you make safe choices without the extra work”
meta_image: "cover_image.png" # should exist in `app/assets/images/`
